TYPE=VIEW
query=select `hms_db`.`customers`.`NAME` AS `name`,`hms_db`.`customers`.`SALARY` AS `salary` from `hms_db`.`customers`
md5=a7952485ef8103ee0a0f646db691bc18
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=2
with_check_option=0
timestamp=2015-06-04 07:51:18
create-version=1
source=select name, salary from CUSTOMERS
client_cs_name=utf8
connection_cl_name=utf8_general_ci
view_body_utf8=select `hms_db`.`customers`.`NAME` AS `name`,`hms_db`.`customers`.`SALARY` AS `salary` from `hms_db`.`customers`
